 version: '2'
 services:
    db:
        image: postgres

    web:
        build: .
        command: python3 ./manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/aggregator
        ports:
            - "8000:8000"
        depends_on:
            - db
        extra_hosts:
            - "www.localhost:127.0.0.1"
            - "msk.localhost:127.0.0.1"
            - "spb.localhost:127.0.0.1"




