 version: '2'
 services:
    
    web:
        build: .
        volumes:
            - .:/aggregator
        ports:
            - "8000:8000"

        extra_hosts:
            - "www.localhost:127.0.0.1"
            - "msk.localhost:127.0.0.1"
            - "spb.localhost:127.0.0.1"
        
        command: python3 ./manage.py migrate
        command: python3 ./manage.py loaddata city
        command: python3 ./manage.py runserver 0.0.0.0:8000

        depends_on:
            - db

    db:
        image: postgres

        environment:
            POSTGRES_USER: aggregator
            POSTGRES_PASSWORD: aggregator
            POSTGRES_DB: aggregator




# RUN python manage.py loaddata city