# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('public', 'public'), ('delete', 'delete')], default='draft', max_length=10)),
                ('media', models.ImageField(blank=True, help_text='Upload your photo for post', null=True, upload_to='media/%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detail Article',
                'verbose_name_plural': 'Article',
            },
        ),
    ]
