# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='public_at',
            field=models.DateField(blank=True, default='2017-01-01'),
            preserve_default=False,
        ),
    ]
