# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20170722_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default='2017-01-01'),
            preserve_default=False,
        ),
    ]
