# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20170722_1811'),
        ('articles', '0008_auto_20170722_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.City'),
        ),
    ]
