# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20170715_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, null=True)),
                ('photo', models.ImageField(null=True, upload_to='img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='GamerProfile',
        ),
        migrations.DeleteModel(
            name='PartnerProfile',
        ),
    ]
